const data = {
  code: 0,
  result: {
    standardAdList: [],
    liteAdList: [
      {
        _id: "62a2a72715103d001d783694",
        gymName: "송내 신라헬스클럽",
        gymPhotoBig:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1814b5cf0761008f4d/2YATTjJnyCeCa2jH6awBvshQSV6ELYQsAEG4.Big_74109460.jpg",
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1814b5cf0761008f4d/2Zw8qmUXk86TNWXJUhNMMBs97BBDwAGWLxce.Small_74109460.jpg",
        address: "경기 부천시 상동",
        location: [126.75152844825578, 37.4905293112524],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "운동복 / 수건 / 찜질방 / 개인락커",
        },
        price: {
          name: "헬스+운동복+개인라커",
          count: null,
          isLowestPrice: true,
          lowestPrice: 342000,
          originalPrice: 360000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 49,
        },
        review: {
          rate: 4.9,
          count: 39,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
        coupons: null,
      },
    ],
    centerList: [
      {
        _id: "607e39c0c70b9e0039942978",
        gymName: "일신 엘케이짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/178ed1197661950cf3/4K7pEJtywheyiTpxFR77dyrYXAUzUyZ2H6ZF7KydMs6g.jpg",
        address: "인천 부평구 일신동",
        location: [126.74234310156417, 37.48623588383842],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "O.T (상시지도)",
        },
        service: {
          free: "수건 / 운동복 / 체성분 분석 / Wi-fi / 주차(18시 이후 무료주차)",
        },
        price: {
          name: "헬스+운동복",
          count: null,
          isLowestPrice: true,
          lowestPrice: 329000,
          originalPrice: 363000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 7,
        },
        review: {
          rate: 5,
          count: 2,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "5ea908f7681b2c001c0fc3f9",
        gymName: "송내 짐에스헬스장",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/171c44b06c3e6b29/Ary1hr6QbUavuyZjCaRUJK7ybdHiRLmwcBKANY9Wx.jpg",
        address: "경기 부천시 송내동",
        location: [126.752895, 37.486884],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "수건 / Wi-Fi",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 330000,
          originalPrice: 330000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 4.75,
          count: 4,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "634f1fe9540818001d643751",
        gymName: "송내역 프라임짐 3호점",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/183ed14a8faab11a8/2ZwwcGKLNvkobLAHQHKfE283XNBzWCkhwUiC.list_photo.jpg",
        address: "경기 부천시 상동",
        location: [126.75254854741013, 37.48808071714801],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "헬스등록시, 6개월마다 PT 1회 무료",
        },
        service: {
          free: "12개월권 등록시, 수건 무료 / ️건물 타워 주차 가능 (대형차량, suv 불가) / ️공영 주차장 1시간 무료(대형차량,suv고객님)",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 376200,
          originalPrice: 396000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 2,
        },
        review: {
          rate: 5,
          count: 10,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "615e6c826bdf9700390c9e95",
        gymName: "부개 골드짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17c58d7dcf52f4d98d/4K7xorRJgwgywmRHpZMi7K7cwoVQDFHobqagY4tZmiBi.jpg",
        address: "인천 부평구 부개동",
        location: [126.73837978862596, 37.493667442301806],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 332500,
          originalPrice: 350000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 20,
        },
        review: {
          rate: 5,
          count: 1,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "60a607bdc70b9e003994f0cc",
        gymName: "송내 크로스핏거츠",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/179888e3c7232b89a7/4K7pPt1jTmVJNr7cjhNwhJMmq1MfieUma2XXi4cngkcp.jpg",
        address: "경기 부천시 상동",
        location: [126.75501822658316, 37.48818419291861],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["크로스핏"],
        program: {
          free: "",
        },
        service: {
          free: "수건 / Wi-fi / 주차 2시간",
        },
        price: {
          name: "크로스핏 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 2360000,
          originalPrice: 2360000,
          period: 12,
          priceType: "period",
          itemTags: ["크로스핏"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "66974a7301d0e4001dbc7b94",
        gymName: "부평 초심PTX메루치양식장",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/190befad34b36fe7a8/3yyza2VdoTs7BR8GLWcJqZAfeL5wD6JtCM85.Small_2.jpg",
        address: "인천 부평구 부평동",
        location: [126.72404761785982, 37.485359619013],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["P.T"],
        program: {
          free: "",
        },
        service: {
          free: "️주차 / ️공용락커",
        },
        price: {
          name: "1:1PT",
          count: 36,
          isLowestPrice: true,
          lowestPrice: 1812600,
          originalPrice: 1908000,
          period: null,
          priceType: "count",
          itemTags: ["P.T"],
          lowestPriceRemainingCount: 5,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "65ee9ca2b2e9a2001dc1f7e3",
        gymName: "부평남부 바디홀릭 필라테스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18e2c13da7355cff1/2ZwYTEgcGbZ7qNpRvcZ4bBEQvCRn7CCmFdff.센터 Small 복사.jpg",
        address: "인천 부평구 부평동",
        location: [126.72463962670848, 37.48733420227458],
        isWomenOnly: false,
        isReservationRequired: true,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["필라테스"],
        program: {
          free: "",
        },
        service: {
          free: "️수건/ 샤워시설 / 반신욕기 / ️공용락커",
        },
        price: {
          name: "6:1 필라테스",
          count: 120,
          isLowestPrice: false,
          lowestPrice: 1160000,
          originalPrice: 1160000,
          period: null,
          priceType: "count",
          itemTags: ["필라테스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "637c6f2be38504001de06524",
        gymName: "부개 복싱인사이드짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1849e12404f415c4a3/2Y9FSvKEwfQqykN6KAP67bkUqJpE3eyEB5Jm.Small_다운로드.jpg",
        address: "인천 부평구 부개동",
        location: [126.73794680242598, 37.49738364133078],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["복싱"],
        program: {
          free: "",
        },
        service: {
          free: "",
        },
        price: {
          name: "평일기간권(주5회)",
          count: null,
          isLowestPrice: true,
          lowestPrice: 1395000,
          originalPrice: 1500000,
          period: 12,
          priceType: "period",
          itemTags: ["복싱"],
          lowestPriceRemainingCount: 10,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "62749c2cdf6c66001d16ce84",
        gymName: "송내 트라이던 피트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18097820c5f539eee6/4K8ftUBec3kHQiWKYgSpKXnT9tmmxZY8vN5zogAvTGs2.jpg",
        address: "경기 부천시 송내동",
        location: [126.76166277058756, 37.48342098005611],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "OT 1회 제공(50분)",
        },
        service: {
          free: "개인 샤워실 / 주차 가능, 시간 제한 없음",
        },
        price: {
          name: "헬스",
          count: null,
          isLowestPrice: false,
          lowestPrice: 360000,
          originalPrice: 360000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 3,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "60c0a19ac70b9e003995a855",
        gymName: "부개 팀타이거복싱짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/179f0774361ef22f2/kXYbCnxsTYFHiFCvUChrcYKP1MrhMobhTw2sqAaWLQ.jpg",
        address: "인천 부평구 부개동",
        location: [126.73551054447834, 37.497418727855234],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["복싱"],
        program: {
          free: "G.X (20시)",
        },
        service: {
          free: "Wi-fi / 수건 / 락커",
        },
        price: {
          name: "복싱",
          count: null,
          isLowestPrice: false,
          lowestPrice: 1050000,
          originalPrice: 1050000,
          period: 12,
          priceType: "period",
          itemTags: ["복싱"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "66c7ef9801d0e4001dd151e9",
        gymName: "부개 용인대 런주짓수&런킥복싱",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1917cffea84371eb27/2WQKokHScfsuvizd5Ju7G91kEn2R8y9pdyoB.list_photo.jpg",
        address: "인천 부평구 부개동",
        location: [126.73546237340084, 37.498008806885316],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["주짓수", "킥복싱"],
        program: {
          free: "",
        },
        service: {
          free: "주차 무료 서비스",
        },
        price: {
          name: "용인대 런주짓수 & 런킥복싱 회원권",
          count: null,
          isLowestPrice: false,
          lowestPrice: 1200000,
          originalPrice: 1200000,
          period: 12,
          priceType: "period",
          itemTags: ["주짓수", "킥복싱"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6695f2f6cae983001dff5427",
        gymName: "부천 듀오피트니스",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/190b9bd11e213ac9c3/2aHaT15JNFsJuDdkz4Wc1bVjVCd46NpYoNAh.list_photo.jpg",
        address: "경기 부천시 원미구 상동",
        location: [126.76046613945502, 37.49080906209784],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "주차 : 오후 6시까지 공영주차장 무료이용 가능 / 샤워 수건",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 379000,
          originalPrice: 396000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 10,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "63b3bc22c47379001d407e8a",
        gymName: "중동역 울트라짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1857616e5251d4ae74/4K8gtVBWetUJQZqg7DghoVRAx14ZoUaXnLq2tKkpYBKE.jpg",
        address: "경기 부천시 송내동",
        location: [126.76425209390554, 37.484273121166815],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T", "기구필라테스"],
        program: {
          free: "",
        },
        service: {
          free: "운동복 / 수건 / 샤워실 / ️ 주차 2시간 30분 가능 / 인바디",
        },
        price: {
          name: "헬스 (+운동복)",
          count: null,
          isLowestPrice: true,
          lowestPrice: 386000,
          originalPrice: 396000,
          period: 12,
          priceType: "period",
          itemTags: [],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 16,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "654c5a795b1869001db38133",
        gymName: "부평 스페시맨GYM",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18bb2416b9a4aa6cfe/i7hkxkCheAG42NgYuKnRvg7xJekS6N31fV.Small_231121_부평_스페시멘GYM_11.jpg",
        address: "인천 부평구 부평동",
        location: [126.72364660238469, 37.49293162907103],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["P.T"],
        program: {
          free: "",
        },
        service: {
          free: "️운동복 / ️개인락카 / ️수건 / ️주차 (부평 문화의거리 공영주차장 주차 1시간 무료지원)",
        },
        price: {
          name: "1:1 PT",
          count: 40,
          isLowestPrice: false,
          lowestPrice: 2376000,
          originalPrice: 2376000,
          period: null,
          priceType: "count",
          itemTags: ["P.T"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "5a73c5aa6959a655ea649cdb",
        gymName: "부평 더블유짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/161543c22ff45b4645/4K6uVdbJnWndJAmYHdfhiJGFKMyGznaShXc7ckxGwPma.jpg",
        address: "인천 부평구 부평동",
        location: [126.722819, 37.492248],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "스피닝", "그룹P.T"],
        program: {
          free: "O.T (3개월 등록시 1회 / 6개월 등록시 2회)",
        },
        service: {
          free: "주차 (2시간 - SUV/외제차는 제외)",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 342000,
          originalPrice: 360000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: 5,
        },
        review: {
          rate: 4.53,
          count: 24,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6386b97eb54b10001dec4fe3",
        gymName: "부평 mgym",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/184c64497a13d462cd/NV8xnm3W7Lz91cpfB6BB5qKjzHUe7Ws1PP.list_photo.jpg",
        address: "인천 부평구 부평동",
        location: [126.72965251611235, 37.49880655738467],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "O.T",
        },
        service: {
          free: "주차 (2시간)",
        },
        price: {
          name: "헬스",
          count: null,
          isLowestPrice: false,
          lowestPrice: 396000,
          originalPrice: 396000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "61936a38e271c900398564e1",
        gymName: "부평 PT의정석 운동재활센터",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17d27d6ecb9117de10/4K7y1LZk6uGHeY8uKFvvoerx8vAzcMhZhj9HHeW8fBgt.jpg",
        address: "인천 부평구 부평동",
        location: [126.72394228220516, 37.49672824822733],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["P.T"],
        program: {
          free: "",
        },
        service: {
          free: "수건 / 락커 / Wi-fi",
        },
        price: {
          name: "1:1 P.T (횟수제)",
          count: 10,
          isLowestPrice: false,
          lowestPrice: 690000,
          originalPrice: 690000,
          period: null,
          priceType: "count",
          itemTags: ["P.T"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "614400326bdf9700390a77a8",
        gymName: "중동 하이엔드짐",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17bf1a0c5b736581c9/MD7W7VKHW1Q1JwjE5EXZWTaafbdn8D8aYK.list_photo.jpg",
        address: "경기 부천시 중동",
        location: [126.7622307484983, 37.49617351104009],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: true,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "",
        },
        service: {
          free: "수건 / Wi-fi",
        },
        price: {
          name: "헬스 (정원제)",
          count: null,
          isLowestPrice: false,
          lowestPrice: 550000,
          originalPrice: 550000,
          period: 12,
          priceType: "period",
          itemTags: ["헬스"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 5,
          count: 5,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "66b46d2b01d0e4001dc96cc0",
        gymName: "부개 제이폭스멀티짐 ",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/19130ca71dc5b272fa/2bhfPy9XyN2BdyvQWfdx5ex1Ps9psB13ZnFL.list_photo.jpg",
        address: "인천 부평구 부개동",
        location: [126.73889210596084, 37.50358013426223],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: false,
        exhibitionRemainingCount: null,
        tags: ["헬스"],
        program: {
          free: "",
        },
        service: {
          free: "3개월 등록시 글러브, 붕대 무료증정",
        },
        price: {
          name: "제이폭스멀티짐 회원권(킥복싱,주짓구,복싱,무에타이)",
          count: null,
          isLowestPrice: false,
          lowestPrice: 300000,
          originalPrice: 300000,
          period: 3,
          priceType: "period",
          itemTags: ["복싱", "킥복싱"],
          lowestPriceRemainingCount: null,
        },
        review: {
          rate: 0,
          count: 0,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
      {
        _id: "6286411618d341001d0b01dc",
        gymName: "부개 바디패션짐 본점 24시",
        gymPhotoBig: null,
        gymPhotoSmall:
          "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/180dc6e41623842c1/kXjoYTf8yjZtEqBum7mBuLWhMTpies1cq14XPmrQDN.jpg",
        address: "인천 부평구 부개동",
        location: [126.73964833296745, 37.50401428488515],
        isWomenOnly: false,
        isReservationRequired: false,
        hasDailyItem: false,
        isLiked: null,
        isLowestPrice: true,
        exhibitionRemainingCount: null,
        tags: ["헬스", "P.T"],
        program: {
          free: "O.T 1회(선택사항)",
        },
        service: {
          free: "",
        },
        price: {
          name: "헬스 회원권",
          count: null,
          isLowestPrice: true,
          lowestPrice: 249000,
          originalPrice: 250000,
          period: 12,
          priceType: "period",
          itemTags: [],
          lowestPriceRemainingCount: 4,
        },
        review: {
          rate: 4.15,
          count: 10,
        },
        videoUrl: null,
        videoThumbnailUrl: null,
      },
    ],
  },
};

export const { centerList } = data.result;
